### ISSUE TITLE
bson: wrong number of arguments in `serialize' (4 for 3)

### ISSUE THREAD

**Issue by christiangenco** [mcmire/time_tracker#3]
Alas, more gem dependency issues:

```
~/time_tracker[master*]% bin/tt
Loading...
/Users/cgenco/.rvm/gems/ruby-1.9.2-p290/gems/bson-1.6.2/lib/bson/bson_c.rb:24:in `serialize': wrong number of arguments(4 for 3) (ArgumentError)
  from /Users/cgenco/.rvm/gems/ruby-1.9.2-p290/gems/bson-1.6.2/lib/bson/bson_c.rb:24:in `serialize'
  from /Users/cgenco/.rvm/gems/ruby-1.9.2-p290/gems/mongo-1.6.2/lib/mongo/cursor.rb:604:in `construct_query_message'
  from /Users/cgenco/.rvm/gems/ruby-1.9.2-p290/gems/mongo-1.6.2/lib/mongo/cursor.rb:465:in `send_initial_query'
  from /Users/cgenco/.rvm/gems/ruby-1.9.2-p290/gems/mongo-1.6.2/lib/mongo/cursor.rb:458:in `refresh'
  from /Users/cgenco/.rvm/gems/ruby-1.9.2-p290/gems/mongo-1.6.2/lib/mongo/cursor.rb:128:in `next'
  from /Users/cgenco/.rvm/gems/ruby-1.9.2-p290/gems/mongo-1.6.2/lib/mongo/db.rb:511:in `command'
  from /Users/cgenco/.rvm/gems/ruby-1.9.2-p290/gems/mongo-1.6.2/lib/mongo/connection.rb:628:in `check_is_master'
  from /Users/cgenco/.rvm/gems/ruby-1.9.2-p290/gems/mongo-1.6.2/lib/mongo/connection.rb:402:in `connect'
  from /Users/cgenco/.rvm/gems/ruby-1.9.2-p290/gems/mongo-1.6.2/lib/mongo/connection.rb:589:in `setup'
  from /Users/cgenco/.rvm/gems/ruby-1.9.2-p290/gems/mongo-1.6.2/lib/mongo/connection.rb:114:in `initialize'
  from /Users/cgenco/Desktop/time_tracker/lib/tt/mongo_mapper.rb:6:in `new'
  from /Users/cgenco/Desktop/time_tracker/lib/tt/mongo_mapper.rb:6:in `<top (required)>'
  from /Users/cgenco/Desktop/time_tracker/lib/tt.rb:4:in `require'
  from /Users/cgenco/Desktop/time_tracker/lib/tt.rb:4:in `<top (required)>'
  from bin/tt:22:in `require'
  from bin/tt:22:in `<main>'
```

Probably to do with:

```
~/time_tracker[master*]% mongo --version
MongoDB shell version: 2.0.4
```

**Comment by mcmire** [comment]
Ah, okay. Well I'm using an older version of mongo_mapper, I can tell you that -- the newest version is likely compatible with that version of Mongo. Sorry for the trouble. I'll look into it.

**Comment by christiangenco** [comment]
No trouble at all! Mad respect for still supporting code you wrote two years ago.

I've started using https://github.com/DanielVF/d-time-tracker in the meanwhile solely for its simplicity but would like to expand it with some of the features you built into time_tracker (I really love the segmentation into projects). Will also take a look at https://github.com/samg/timetrap which you mention in your readme.

**Comment by christiangenco** [comment]
Ended up with something simpler: https://github.com/christiangenco/t-time-tracker

**Comment by mcmire** [comment]
Nice. Agreed about simplicity. I may consider dropping Mongo, it is kind of a huge dependency. Glad I could help in the meantime.
